apiVersion: apps/v1

kind: Deployment

metadata:

  name: frontend

  labels:

    app: frontend

spec:

  replicas: 10

  selector:

    matchLabels:

      app: frontend

  strategy:

    rollingUpdate:

      maxSurge: 20%

      maxUnavailable: 20%

  template:

    metadata:

      labels:

        app: frontend

    spec:

      containers:

      - name: frontend

        image: arnie1974/python-frontend:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 5000
